### ISSUE TITLE
Two-channel audio recordings?

### ISSUE THREAD

**Issue by abidlabs** [vivjay30/Cone-of-Silence#7]
From what I understand, the model will work for 4-channel and 6-channel wav files.

Does this model also work on 2-channel recordings? Is there a pretrained model for that?

**Comment by abidlabs** [comment]
Or even 1 channel? For example, how would I use your model with the .wav file on the project page called "Input Mixture (2 Voices + BG)". When I download the .wav file and pass it through the inference script, it throws an error because there is only 1 channel in the .wav file

**Comment by vivjay30** [comment]
Hi, the project page only has the mono input. For the 4 channel input see sample here: https://drive.google.com/drive/folders/1YeuHPvqmaPMGvcSOb9J-hnLDYSbK1S2c?usp=sharing

We haven't trained with 2 channel recordings because you would get front-back confusion. In theory this is fine, but we don't have a pretrained network for that. If you train up a network and want to share it, I would be happy to add it to the repo!
